version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run build && npx serve -s dist -l 5173"
    volumes:
      - ./:/app
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped